import { createAction } from '@reduxjs/toolkit';
export const updateMatchesDarkMode = createAction('user/updateMatchesDarkMode');
export const updateTheme = createAction('user/updateTheme');
export const updateUserExpertMode = createAction('user/updateUserExpertMode');
export const updateUserSingleHopOnly = createAction('user/updateUserSingleHopOnly');
export const updateUserMinApprove = createAction('user/updateUserMinApprove');
export const updateUserAllowMoolaWithdrawal = createAction('user/updateUserAllowMoolaWithdrawal');
export const updateUserDisableSmartRouting = createAction('user/updateUserDisableSmartRouting');
export const updateUserSlippageTolerance = createAction('user/updateUserSlippageTolerance');
export const updateUserDeadline = createAction('user/updateUserDeadline');
export const addSerializedToken = createAction('user/addSerializedToken');
export const removeSerializedToken = createAction('user/removeSerializedToken');
export const addSerializedPair = createAction('user/addSerializedPair');
export const removeSerializedPair = createAction('user/removeSerializedPair');
export const toggleURLWarning = createAction('app/toggleURLWarning');
export const setValoraAccount = createAction('user/setValoraAccount');
export const clearValoraAccount = createAction('user/clearValoraAccount');
export const updateUserAprMode = createAction('user/updateUserAprMode');
