"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.removePopup = exports.addPopup = exports.setOpenModal = exports.updateBlockNumber = exports.ApplicationModal = void 0;
const toolkit_1 = require("@reduxjs/toolkit");
var ApplicationModal;
(function (ApplicationModal) {
    ApplicationModal[ApplicationModal["WALLET"] = 0] = "WALLET";
    ApplicationModal[ApplicationModal["BRIDGE"] = 1] = "BRIDGE";
    ApplicationModal[ApplicationModal["SETTINGS"] = 2] = "SETTINGS";
    ApplicationModal[ApplicationModal["SELF_CLAIM"] = 3] = "SELF_CLAIM";
    ApplicationModal[ApplicationModal["ADDRESS_CLAIM"] = 4] = "ADDRESS_CLAIM";
    ApplicationModal[ApplicationModal["CLAIM_POPUP"] = 5] = "CLAIM_POPUP";
    ApplicationModal[ApplicationModal["MENU"] = 6] = "MENU";
    ApplicationModal[ApplicationModal["DELEGATE"] = 7] = "DELEGATE";
    ApplicationModal[ApplicationModal["VOTE"] = 8] = "VOTE";
    ApplicationModal[ApplicationModal["CHARTS"] = 9] = "CHARTS";
})(ApplicationModal = exports.ApplicationModal || (exports.ApplicationModal = {}));
exports.updateBlockNumber = (0, toolkit_1.createAction)('application/updateBlockNumber');
exports.setOpenModal = (0, toolkit_1.createAction)('application/setOpenModal');
exports.addPopup = (0, toolkit_1.createAction)('application/addPopup');
exports.removePopup = (0, toolkit_1.createAction)('application/removePopup');
